### ISSUE TITLE
Fix lib config loading

### ISSUE THREAD

**Issue by Vittly** [bem/bem-sdk#204]
Need to replace `new BemConfig({ projectRoot: lib.path });` with kind of `new BemConfig({ cwd: resolve(lib.path) })`. Property `projectRoot` is never used.

[Example](https://github.com/bem-sdk-archive/bem-config/blob/master/index.js#L140)

**Comment by tadatuta** [comment]
was fixed in https://github.com/bem/bem-sdk/commit/4d1cbdd06bb89d689ab43de0d4749ef5ffe37e3f
