### ISSUE TITLE
Remove assert from naming.entity.stringify

### ISSUE THREAD

**Issue by Yeti-or** [bem/bem-sdk#244]
`assert` is dependency on node.js environment

**Comment by Yeti-or** [comment]
Maybe we could wrap it in `process.env.NODE_DEV` ? or any other ideas?

**Comment by qfox** [comment]
`process` is a node.js environment

**Comment by awinogradov** [comment]
@zxqfox @Yeti-or any progress here?

**Comment by qfox** [comment]
@awinogradov Can you show me the problem you have? I don't get what we should do here.
To decide what is the best solution we need to know some environment.

upd: I'm pretty sure `assert` is a common thing which can be safely removed from the code if need and your build-tool can do it automagically.
- https://github.com/unassert-js/unassert
- https://www.npmjs.com/package/webpack-unassert-loader

**Comment by awinogradov** [comment]
That would be true if `naming.entity.stringify` would be the target package. But it's dependency for us. It's not a good pattern to parse node_modules. Also, it's very slow. I don't understand why you can't change `assert` to another one for comfortable usage in browsers or rewrite one row to `if` with native error :(

**Comment by qfox** [comment]
What is the tool that parsing and building bundles from your code?
