### ISSUE TITLE
decl.normalize v2 every time adds _mod_true

### ISSUE THREAD

**Issue by Vittly** [bem/bem-sdk#330]
depsOld from [enb-bem-techs](https://github.com/enb/enb-bem-techs) converts `{ block: 'a', mod: 'c', val: 'd' }` to list

- `{ block: 'a', mod: 'c' }`
- `{ block: 'a', mod: 'c', val: 'd' }`

[@bem/sdk.decl](https://github.com/bem/bem-sdk/tree/master/packages/decl) on same input returns

- `{ block: 'a', mod: 'c', val: true }` — Why? This is not what I want
- `{ block: 'a', mod: 'c', val: 'd' }`

May be [this code](https://github.com/bem/bem-sdk/blob/master/packages/decl/lib/formats/v2/normalize.js#L166-L168) does the trick.

What format should I use to get "depsOld"-way result?

**Comment by Vittly** [comment]
@zxqfox says to use

```js

decl.stringify(cells, { format: 'enb' });
```

Need to add fix [here](https://github.com/bem/bem-sdk/blob/8381e028b5f47adff3eedc4781f8637e19ec7e04/packages/decl/lib/formats/enb/format.js#L19):

```js
entity.mod.val !== true && (tmp.val = entity.mod.val);
```

**Comment by Vittly** [comment]
But if initial declaration got `block_mod_true` such solution will waste it. I need fix at "normalize"-level or new format like "enb-deps"

**Comment by qfox** [comment]
Still thinking that my way fit your needs better ;-)

**Comment by Vittly** [comment]
Finally figured out:

- `{ block: 'b', mod: 'c', val: true }` stands for `b_c.js`
- `{ block: 'b', mod: 'c', val: 'true' }` stands for `b_c_true.js`

**Comment by Vittly** [comment]
So "format('enb')" is ok

**Comment by qfox** [comment]
Yeah. There is a fine point:
`{ block: 'b', mod: 'm' }` (old) and `{ block: 'b', mod: 'm', val: true }` (new) is accurately the same in different formats.

**Comment by Vittly** [comment]
fixed
